### ISSUE TITLE
Feature: User can check information of each cryptocurrency.

### ISSUE THREAD

**Issue by justinsong1608** [justinsong1608/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can check information of each cryptocurrency.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to see live information about the top 50 cryptocurrencies of the day. User will be able to see the ranking, name, price, 24hr percent change, market cap, volume the past 24 hrs, and the circulating supply.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="240" alt="Screenshot 2023-02-28 at 9 24 08 AM" src="https://user-images.githubusercontent.com/122064415/221930096-abb8d637-7ec9-4c67-9d5b-5849fff61965.png">
<img width="907" alt="Screenshot 2023-02-28 at 9 24 38 AM" src="https://user-images.githubusercontent.com/122064415/221930144-7a9aabf4-eebd-4547-880d-1cf687e176f9.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create the HTML for the header in the `header-container` so that it matches the figma example.
- [x] Create the CSS for the header so that it matches the figma example for the mobile device.
- [x] Below the header, create the HTML for the home page in the `body-container` as an example for you to reference.
   - [x] Create about 3 examples to use for reference later.
- [x] Create the CSS for the home page so that it matches the figma example for the mobile device.
- [x] Define a function name `renderCrypto` with a single parameter named `crypto`. The function should generate and return a DOM tree.
   - [x] Use the the HTML example that you created for reference
- [x] In `data.js` create a data object to store your API
- [x] In `data.js`, add a `'beforeunload'` event listener to the `window` object that serializes the data model as JSON and stores the JSON in `localStorage`.
- [x] At the bottom of `data.js`, include a conditional statement that:
  - [x] checks to see if there is a JSON data model stored in `localStorage`.
  - [x] if there is, parse it and assign it to the initial `data` variable so that the user can continue adding entries to the pre-existing data model.
- [x] Create an `XMLHttpRequest` in JavaScript to get the data from the api, api.coincap.io/v2/assets.
   - [x] Put this request inside of a function that uses a for loop to run through the first 50 cryptocurrencies and store the data inside the `coins` array inside the `data` object that was created.
- [x] Create a `for loop` through the 50 cryptocurrencies from `coins` array and generate a DOM tree for each crypto, and append that DOM tree to the HTML.
- [x] Remove the HTML example from the HTML once the top 50 cryptos are appended to the DOM correctly.
- [x] Use the CSS @media Rule to adjust the layout when the screen is on desktop
- [x] Clean up the code
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create a screen recording or a screenshot of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
