### ISSUE TITLE
Feature: User can edit their total

### ISSUE THREAD

**Issue by justinsong1608** [justinsong1608/ajax-project#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can edit their total for each individual coin and total amount will change reflected based on the change of total coins.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
The user can click on the edit icon on the bottom left of their coin in their wallet. A modal will pop-up asking the user to input the amount that the user wants to change. Once the user inputs the new total and submits it, the total amount of usd should reflect the change.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2023-03-08 at 11 52 31 AM](https://user-images.githubusercontent.com/122064415/223872196-107e587a-8f43-46be-b48e-db87ea45ecc2.png)
![Screenshot 2023-03-08 at 11 52 40 AM](https://user-images.githubusercontent.com/122064415/223872206-8fac54f2-7c1f-4ad0-9a82-c130b
![Screenshot 2023-03-08 at 11 52 51 AM](https://user-images.githubusercontent.com/122064415/223872215-9de1621a-1f91-4b1a-bbce-74531087f6e6.png)
162c83a.png)
![Screenshot 2023-03-08 at 11 52 57 AM](https://user-images.githubusercontent.com/122064415/223872225-d51212ac-2462-47de-a46f-38adeb317a8a.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Update the render function for creating the coins in wallet
   - [x] Place the edit icon on the coin similar to the wireframe above
- [x] Create a modal
- [x] Add an eventListener to the edit icon:
   - [x] Opens a modal with a form
- [x] Create a cancel button that closes the modal
- [x] Create a submit button that changes the current total with the new input and update the total amount
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
