### ISSUE TITLE
Feature: User can see the table update with new information every few seconds.

### ISSUE THREAD

**Issue by justinsong1608** [justinsong1608/ajax-project#13]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see the table update with new information every few seconds.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
User will be able to see the table update every few seconds have the most up-to-date information on the top 50 cryptos

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2023-03-09 at 2 19 34 PM](https://user-images.githubusercontent.com/122064415/224173191-f9cb4124-2306-41af-a20f-5c941979eadc.png)
![Screenshot 2023-03-09 at 2 19 25 PM](https://user-images.githubusercontent.com/122064415/224173200-9336b4f8-24f1-4d22-bd25-ede2c4e06630.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x]  Update the `xhr.addEventListener`:
  - [x] Use setInterval to update the table every few seconds with the updated information
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
