### ISSUE TITLE
Feature: User can use a crypto converter.

### ISSUE THREAD

**Issue by justinsong1608** [justinsong1608/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can input how much cryptocurrency they want to buy or sell and see how much they would need to give or to receive back in a different cryptocurrency.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can select the currency that they have and see how much they need to give or to receive the selected currency they desire.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2023-03-01 at 11 30 27 AM](https://user-images.githubusercontent.com/122064415/222244897-4cf0305d-b7a8-427d-b216-ae4e6e11ee36.png)
![Screenshot 2023-03-01 at 4 22 43 PM](https://user-images.githubusercontent.com/122064415/222297831-3f3d1d6a-847e-43ed-8b97-b1a4f9fc29c6.png)
![Screenshot 2023-03-01 at 11 31 08 AM](https://user-images.githubusercontent.com/122064415/222244924-27e4eec9-a45e-4486-bf9c-23256a6114e4.png)
![Screenshot 2023-03-01 at 4 22 55 PM](https://user-images.githubusercontent.com/122064415/222297858-ba0d3ee8-0419-4e10-a516-15a33339a328.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] In `data.js` file add a `view` property and set its value to the home page.
   - [x] Add the specific `view` to the home page and the converter
- [x]  Create a new function named viewSwap with a single parameter representing the name of the view to show. This function should show the view whose name was provided as an argument, as well as assign the string argument to the data.view property so that the currently shown view is tracked in the data model for the application.
- [x] Create an event handler function that utilizes the viewSwap function to show the proper view for the anchor tag `converter` and home page.
- [x] Create the HTML of the converter page as same as the images above.
- [x] Add CSS to the converter page as same as the images above.
- [x] Add an event listener to the convert button that converts the amount to the currency that was selected.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
