### ISSUE TITLE
Feature: User can add a cryptocurrency to their wallet.

### ISSUE THREAD

**Issue by justinsong1608** [justinsong1608/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add a cryptocurrency to their wallet.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
User can click on the plus icon on the home page next to the desired cryptocurrency to their wallet.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="637" alt="Screenshot 2023-03-02 at 6 11 50 PM" src="https://user-images.githubusercontent.com/122064415/222614606-5b60a624-7386-455c-89f1-1e8f18b0e550.png">
<img width="637" alt="Screenshot 2023-03-02 at 6 11 59 PM" src="https://user-images.githubusercontent.com/122064415/222614616-ad6e1332-1414-4311-856b-19b714026491.png">
<img width="177" alt="Screenshot 2023-03-02 at 6 15 44 PM" src="https://user-images.githubusercontent.com/122064415/222614625-ea58421a-13db-4152-8069-51fe7d30b38d.png">
<img width="180" alt="Screenshot 2023-03-02 at 6 15 50 PM" src="https://user-images.githubusercontent.com/122064415/222614632-58722e50-7052-450f-8d3e-bcbba0ee0599.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create an addEventListener  for `DOMContentLoaded` and create a callback function to do the following:
   - [x] uses the viewSwap function to show the view which was displayed prior to page refresh.
- [x] Create a Wallet `view` in HTML
   - [x] Update viewSwap function to switch the view to the wallet page.
   - [x] Create an event handler function that utilizes the viewSwap function to show the proper view for the anchor tag wallet and home page.
- [x] Create the Wallet page in HTML
- [x] Add CSS to Wallet page to make it look like the figma example.
- [x] Create a new data property with an empty array. Call it `myWallet`.
- [x] Create an add event listener for the plus icon. It listens if it was clicked.
  - [x] Once it is clicked, the plus icon disappears.
  - [x] It pushes the crypto information to `myWallet`.
- [x] Create a render function for the coins that are added to the wallet.
- [x] Update  the addEventListener for the plus icon to render the crypto from `myWallet` to the wallet page.
- [x] In the wallet, the plus icon now should look like a minus icon.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
