### ISSUE TITLE
Feature: User can add how much crypto they have for each cryptocurrency, and see their total holdings.

### ISSUE THREAD

**Issue by justinsong1608** [justinsong1608/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add how much crypto they have for each cryptocurrency, and see their total holdings.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When adding a crypto by selecting the plus icon, a modal will up up asking the user to input the amount of crypto you have for the selected crypto. User can enter any number and then it will display in your wallet how much coins you have for that specific coin. Then the wallet can add the total amount of coins you have in your wallet and convert it into USD to see how much money you have.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2023-03-02 at 4 54 04 PM](https://user-images.githubusercontent.com/122064415/222604503-28ff8455-8691-4185-9695-e3371bb17671.png)
![Screenshot 2023-03-02 at 4 54 16 PM](https://user-images.githubusercontent.com/122064415/222604513-3897c98d-a99b-44fc-b910-7abdc6903c27.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a modal and overlay as the one in figma.
- [x] Update the addEventListener for the plus icon to do the following:
   - [x] A modal pops-up asking the user to input the total amount of coins they have.
   - [x] Create a submit button.
        - [x] If submit button is selected, plus icon disappears and is added to the wallet
        - [x] Update `renderMyWallet` to add the total input that the user inputted.
   - [x] Create a cancel button.
        - [x] Hides the modal and nothing is added to the wallet.
- [x] Create a function that adds up the total coins and convert them into USD to see how much they have.
   - [x] Update the textContent of `#my-wallet` to have the total amount displayed
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
