### ISSUE TITLE
Feature: User can delete a cryptocurrency from their watchlist.

### ISSUE THREAD

**Issue by justinsong1608** [justinsong1608/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete a cryptocurrency from their watchlist
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can go their wallet page and select on the minus icon at the bottom right corner of each wallet and delete that coin from their wallet. Their total holdings will be adjusted.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2023-03-03 at 4 03 55 PM](https://user-images.githubusercontent.com/122064415/222857612-6a2820e7-c672-4c27-8923-318b8073c2be.png)
![Screenshot 2023-03-03 at 4 04 03 PM](https://user-images.githubusercontent.com/122064415/222857620-2842f6f6-bcd5-4591-951e-dabeab0b41c3.png)
![Screenshot 2023-03-03 at 4 04 15 PM](https://user-images.githubusercontent.com/122064415/222857624-370dbcea-28ff-4827-a98c-a75f5934cdc5.png)
![Screenshot 2023-03-03 at 4 04 30 PM](https://user-images.githubusercontent.com/122064415/222857629-737c6038-30ac-4313-8be7-20a6a8e0edac.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a modal and overlay as the one in figma.
- [x] Create an `addEventListener` for the minus icon: 
   - [x] The minus icon will pop-up the modal that was created above.
   - [x] Create a cancel button:
       - [x] Cancel button will cancel the act of deleting. 
       - [x] Modal will disappear.
   - [x] Create a submit button:
       - [x] Deletes the crypto from the wallet.
       - [x] The plus icon will reappear in the home page for the deleted coin
       - [x] And if needed, update the total holdings.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
